version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: "book-crud-db"
    ports:
      - "${DB_PORT}:5432"
    stop_grace_period: 30s
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - database_postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: "book-crud-redis"
    ports:
      - "${REDIS_PORT}:6379"
    stop_grace_period: 30s
    environment:
      - REDIS_DBS=${REDIS_DBS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network
    volumes:
      - cache_redis:/var/lib/redis/data

  app:
    build: .
    container_name: "book-crud-app"
    stop_grace_period: 30s
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SSL_MODE: ${SSL_MODE}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    networks:
      - app-network

volumes:
  database_postgres:
  cache_redis:

networks:
  app-network:
    driver: bridge